---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: data/repertoire
  label: Repertuar
  create: documents
  match: "*"
  new_doc_ext: txt
- type: directory
  path: data/people
  label: Ludzie
  create: documents
  match: "*"
  new_doc_ext: txt
- type: directory
  path: posts
  label: Posts
  create: documents
  match: "*"
upload_dir: public/img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
